[package]
name = "issue_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
serde = "1.0.152"
uuid = "1.3.0"
web = "0.2.12"
